org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=ie_hcq_tool_tweaks
mod_name=Immersive Engineering: Tool Tweaks
mod_license=MIT
mod_version=2.0.0
mod_group_id=com.github.hespercq.ie_hcq_tool_tweaks
mod_authors=HesperCQ
mod_description=An Immersive Engineering Add-On that introduces Drillheads and Railgun Ammo that can be configured via datapacks.
mod_issues=https://github.com/HesperCQ/ImmersiveEngineering-ToolTweaks/issues
mod_homepage=https://github.com/HesperCQ/ImmersiveEngineering-ToolTweaks
mod_credits=Credit goes to the creators of Immersive Engineering

## Immersive Engineering Properties
immersive_engineering_version=1.20.1-10.2.0-182

## JEI Properties
jei_version=15.2.0.23
