# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties
forge_version=47.4.0
forge_version_range=[47.4,)
loader_version_range=[47,)

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

ie_version=1.20.1-10.2.0-183
tough_railgun_rods_version=0.2

mapping_channel=official
mapping_version=1.20.1



## Mod Properties
mod_id=ie_hcq_tool_tweaks
mod_name=Immersive Engineering: Tool Tweaks
mod_license=MIT
# mod_version= Unused - instead use version in build.gradle
mod_group_id=io.github.hespercq
mod_authors=HesperCQ
mod_description=An Immersive Engineering Add-On that makes less Mobs immune to Railgun Rods by ensuring they are not considered arrows.